(function (root, factory) {
  if (typeof module === "object" && module.exports) {
    module.exports = factory();
    return;
  }
  root.OrionLocalization = factory();
})(typeof globalThis !== "undefined" ? globalThis : this, () => {
  const SUPPORTED_LOCALES = Object.freeze(["en", "fr", "de", "ja"]);
  const DEFAULT_LOCALE = "en";
  const INTL_LOCALES = Object.freeze({
    en: "en-US",
    fr: "fr-FR",
    de: "de-DE",
    ja: "ja-JP"
  });

  const LANGUAGE_OPTIONS = Object.freeze([
    { locale: "en", label: "English" },
    { locale: "fr", label: "Français" },
    { locale: "de", label: "Deutsch" },
    { locale: "ja", label: "日本語" }
  ]);

  const TRANSLATIONS = Object.freeze({
    en: Object.freeze({
      "app.name": "Orion",
      "app.newTab": "New Tab",
      "app.loading": "Loading...",
      "address.placeholder": "Search or enter URL",
      "find.placeholder": "Find...",
      "find.empty": "0/0",
      "toolbar.newTab": "New Tab",
      "toolbar.newIncognitoTab": "New Incognito Tab (Ctrl/Cmd+Shift+N)",
      "toolbar.closeOthers": "Close Others",
      "profile.addNew": "Add New Profile",
      "profile.default": "Default",
      "profile.named": "Profile {{index}}",
      "profile.incognito": "Incognito",
      "onboarding.kicker": "Welcome",
      "onboarding.title": "Choose your language",
      "onboarding.subtitle": "Pick the language Orion should use. You can change it later in Settings.",
      "onboarding.persist": "Your choice is saved for this device and usually survives reinstalling the app.",
      "history.title": "History",
      "history.close": "Close history panel",
      "history.remove": "Remove from history",
      "history.range.hour": "Hour",
      "history.range.today": "Today",
      "history.range.week": "Week",
      "history.range.all": "Clear All",
      "history.confirm.hour": "Clear the last hour of history?",
      "history.confirm.today": "Clear today's history?",
      "history.confirm.week": "Clear this week's history?",
      "history.confirm.all": "Clear all history?",
      "bookmarks.title": "Bookmarks",
      "bookmarks.close": "Close bookmarks panel",
      "bookmarks.empty": "No bookmarks yet.",
      "downloads.title": "Downloads",
      "downloads.close": "Close downloads panel",
      "downloads.done": "Done",
      "adblock.kicker": "Privacy",
      "adblock.title": "Adblock",
      "adblock.close": "Close adblock panel",
      "adblock.description": "Create custom block rules to remove ads, popups, and known trackers. Add one rule per line and apply instantly.",
      "adblock.badge": "One rule per line",
      "adblock.placeholder": "||ads.example.com^\n||tracker.example.net^\n! comment lines start with !",
      "adblock.tip": "Tip: lines starting with \"!\" are comments. Inline comments are allowed after a rule.",
      "adblock.save": "Save & Apply Rules",
      "adblock.saved": "Saved!",
      "settings.kicker": "Browser Controls",
      "settings.title": "Settings",
      "settings.close": "Close settings panel",
      "settings.heroKicker": "Personalization",
      "settings.heroTitle": "Make Orion yours",
      "settings.heroBody": "Customize the look and behavior of your browser in one place. Changes apply immediately.",
      "settings.themeTitle": "Theme",
      "settings.themeSubtitle": "Pick an accent and tune layout preferences.",
      "settings.colorPicker": "Color Picker",
      "settings.colorPlaceholder": "Color name or hex",
      "settings.applyColor": "Apply Color",
      "settings.discoMode": "Disco Mode",
      "settings.stopDisco": "Stop Disco",
      "settings.verticalTabs": "Vertical Tabs",
      "settings.verticalTabsSub": "Dock tabs on the left side",
      "settings.showSeconds": "Show Seconds",
      "settings.showSecondsSub": "Display seconds in time widgets",
      "settings.languageTitle": "Language",
      "settings.languageSubtitle": "Choose the language used for Orion's interface.",
      "settings.searchTitle": "Search",
      "settings.searchSubtitle": "Choose the engine used by the address bar for plain text queries.",
      "settings.searchLabel": "Default search engine",
      "settings.systemTitle": "System",
      "settings.systemSubtitle": "Check your version and open browser extension management.",
      "settings.checkUpdates": "Check for Updates",
      "settings.openExtensions": "Open Extensions",
      "updates.ready": "Ready to check for updates.",
      "updates.checking": "Checking...",
      "updates.downloading": "Downloading...",
      "updates.restart": "Restart to Update",
      "updates.uptodate": "Up to Date",
      "updates.restarting": "Restarting...",
      "modal.rename": "Rename",
      "modal.cancel": "Cancel",
      "modal.save": "Save",
      "modal.bookmark": "Bookmark",
      "bookmark.bar": "Bar",
      "bookmark.newTab": "New Tab",
      "bookmark.both": "Both",
      "download.loading": "Loading...",
      "extension.pageTitle": "Extensions",
      "extension.eyebrow": "Extensions",
      "extension.header": "Manage Installed Extensions",
      "extension.badge": "Unpacked Mode",
      "extension.loadTitle": "Load Unpacked Extension",
      "extension.loadBody": "To install an extension, download it, unzip it, and paste the full folder path below.",
      "extension.loadExample": "(e.g., /Users/username/Downloads/my-extension)",
      "extension.pathPlaceholder": "absolute/path/to/extension/folder",
      "extension.loadButton": "Load Extension",
      "extension.installedTitle": "Installed Extensions",
      "extension.installedNote": "Loaded from local folders in this browser profile.",
      "extension.remove": "Remove",
      "extension.removeConfirm": "Are you sure you want to remove this extension?",
      "extension.empty": "No extensions installed.",
      "extension.error": "Error loading extensions.",
      "extension.success": "Extension loaded successfully!",
      "extension.loadFailure": "Failed to load extension: {{error}}",
      "extension.invokeFailure": "Error invoking extension load: {{error}}",
      "extension.unknown": "Unknown extension",
      "extension.noDescription": "No description provided.",
      "newtab.pageTitle": "New Tab",
      "newtab.searchPlaceholder": "Search the web",
      "newtab.removeShortcut": "Remove {{name}}"
    }),
    fr: Object.freeze({
      "app.name": "Orion",
      "app.newTab": "Nouvel onglet",
      "app.loading": "Chargement...",
      "address.placeholder": "Rechercher ou saisir une URL",
      "find.placeholder": "Rechercher...",
      "find.empty": "0/0",
      "toolbar.newTab": "Nouvel onglet",
      "toolbar.newIncognitoTab": "Nouvel onglet privé (Ctrl/Cmd+Maj+N)",
      "toolbar.closeOthers": "Fermer les autres",
      "profile.addNew": "Ajouter un profil",
      "profile.default": "Par défaut",
      "profile.named": "Profil {{index}}",
      "profile.incognito": "Navigation privée",
      "onboarding.kicker": "Bienvenue",
      "onboarding.title": "Choisissez votre langue",
      "onboarding.subtitle": "Choisissez la langue utilisée par Orion. Vous pourrez la modifier plus tard dans les réglages.",
      "onboarding.persist": "Votre choix est enregistré pour cet appareil et survit généralement à une réinstallation de l'application.",
      "history.title": "Historique",
      "history.close": "Fermer le panneau d'historique",
      "history.remove": "Retirer de l'historique",
      "history.range.hour": "Heure",
      "history.range.today": "Aujourd'hui",
      "history.range.week": "Semaine",
      "history.range.all": "Tout effacer",
      "history.confirm.hour": "Effacer l'historique de la dernière heure ?",
      "history.confirm.today": "Effacer l'historique d'aujourd'hui ?",
      "history.confirm.week": "Effacer l'historique de cette semaine ?",
      "history.confirm.all": "Effacer tout l'historique ?",
      "bookmarks.title": "Favoris",
      "bookmarks.close": "Fermer le panneau des favoris",
      "bookmarks.empty": "Aucun favori pour le moment.",
      "downloads.title": "Téléchargements",
      "downloads.close": "Fermer le panneau des téléchargements",
      "downloads.done": "Terminé",
      "adblock.kicker": "Confidentialité",
      "adblock.title": "Bloqueur de pub",
      "adblock.close": "Fermer le panneau du bloqueur de pub",
      "adblock.description": "Créez des règles personnalisées pour supprimer les publicités, les pop-ups et les traqueurs connus. Ajoutez une règle par ligne et appliquez-la instantanément.",
      "adblock.badge": "Une règle par ligne",
      "adblock.placeholder": "||ads.example.com^\n||tracker.example.net^\n! les lignes de commentaire commencent par !",
      "adblock.tip": "Astuce : les lignes commençant par \"!\" sont des commentaires. Les commentaires en ligne sont aussi autorisés après une règle.",
      "adblock.save": "Enregistrer et appliquer",
      "adblock.saved": "Enregistré !",
      "settings.kicker": "Contrôles du navigateur",
      "settings.title": "Réglages",
      "settings.close": "Fermer le panneau des réglages",
      "settings.heroKicker": "Personnalisation",
      "settings.heroTitle": "Faites d'Orion le vôtre",
      "settings.heroBody": "Personnalisez l'apparence et le comportement de votre navigateur depuis un seul endroit. Les changements sont appliqués immédiatement.",
      "settings.themeTitle": "Thème",
      "settings.themeSubtitle": "Choisissez une couleur d'accentuation et ajustez la disposition.",
      "settings.colorPicker": "Sélecteur de couleur",
      "settings.colorPlaceholder": "Nom de couleur ou code hexadécimal",
      "settings.applyColor": "Appliquer la couleur",
      "settings.discoMode": "Mode disco",
      "settings.stopDisco": "Arrêter le disco",
      "settings.verticalTabs": "Onglets verticaux",
      "settings.verticalTabsSub": "Afficher les onglets sur le côté gauche",
      "settings.showSeconds": "Afficher les secondes",
      "settings.showSecondsSub": "Afficher les secondes dans les widgets d'heure",
      "settings.languageTitle": "Langue",
      "settings.languageSubtitle": "Choisissez la langue utilisée par l'interface d'Orion.",
      "settings.searchTitle": "Recherche",
      "settings.searchSubtitle": "Choisissez le moteur utilisé par la barre d'adresse pour les requêtes en texte brut.",
      "settings.searchLabel": "Moteur de recherche par défaut",
      "settings.systemTitle": "Système",
      "settings.systemSubtitle": "Vérifiez votre version et ouvrez la gestion des extensions du navigateur.",
      "settings.checkUpdates": "Rechercher des mises à jour",
      "settings.openExtensions": "Ouvrir les extensions",
      "updates.ready": "Prêt à rechercher des mises à jour.",
      "updates.checking": "Recherche...",
      "updates.downloading": "Téléchargement...",
      "updates.restart": "Redémarrer pour mettre à jour",
      "updates.uptodate": "À jour",
      "updates.restarting": "Redémarrage...",
      "modal.rename": "Renommer",
      "modal.cancel": "Annuler",
      "modal.save": "Enregistrer",
      "modal.bookmark": "Favori",
      "bookmark.bar": "Barre",
      "bookmark.newTab": "Nouvel onglet",
      "bookmark.both": "Les deux",
      "download.loading": "Chargement...",
      "extension.pageTitle": "Extensions",
      "extension.eyebrow": "Extensions",
      "extension.header": "Gérer les extensions installées",
      "extension.badge": "Mode non empaqueté",
      "extension.loadTitle": "Charger une extension non empaquetée",
      "extension.loadBody": "Pour installer une extension, téléchargez-la, décompressez-la, puis collez le chemin complet du dossier ci-dessous.",
      "extension.loadExample": "(par ex. /Users/username/Downloads/my-extension)",
      "extension.pathPlaceholder": "chemin/absolu/vers/le/dossier/extension",
      "extension.loadButton": "Charger l'extension",
      "extension.installedTitle": "Extensions installées",
      "extension.installedNote": "Chargées depuis des dossiers locaux dans ce profil du navigateur.",
      "extension.remove": "Supprimer",
      "extension.removeConfirm": "Voulez-vous vraiment supprimer cette extension ?",
      "extension.empty": "Aucune extension installée.",
      "extension.error": "Erreur lors du chargement des extensions.",
      "extension.success": "Extension chargée avec succès !",
      "extension.loadFailure": "Échec du chargement de l'extension : {{error}}",
      "extension.invokeFailure": "Erreur lors de l'appel du chargement de l'extension : {{error}}",
      "extension.unknown": "Extension inconnue",
      "extension.noDescription": "Aucune description fournie.",
      "newtab.pageTitle": "Nouvel onglet",
      "newtab.searchPlaceholder": "Rechercher sur le Web",
      "newtab.removeShortcut": "Retirer {{name}}"
    }),
    de: Object.freeze({
      "app.name": "Orion",
      "app.newTab": "Neuer Tab",
      "app.loading": "Wird geladen...",
      "address.placeholder": "Suchen oder URL eingeben",
      "find.placeholder": "Suchen...",
      "find.empty": "0/0",
      "toolbar.newTab": "Neuer Tab",
      "toolbar.newIncognitoTab": "Neuer Inkognito-Tab (Strg/Cmd+Umschalt+N)",
      "toolbar.closeOthers": "Andere schließen",
      "profile.addNew": "Neues Profil hinzufügen",
      "profile.default": "Standard",
      "profile.named": "Profil {{index}}",
      "profile.incognito": "Inkognito",
      "onboarding.kicker": "Willkommen",
      "onboarding.title": "Sprache auswählen",
      "onboarding.subtitle": "Wähle die Sprache, die Orion verwenden soll. Du kannst sie später in den Einstellungen ändern.",
      "onboarding.persist": "Deine Auswahl wird für dieses Gerät gespeichert und bleibt bei einer Neuinstallation normalerweise erhalten.",
      "history.title": "Verlauf",
      "history.close": "Verlauf schließen",
      "history.remove": "Aus dem Verlauf entfernen",
      "history.range.hour": "Stunde",
      "history.range.today": "Heute",
      "history.range.week": "Woche",
      "history.range.all": "Alles löschen",
      "history.confirm.hour": "Den Verlauf der letzten Stunde löschen?",
      "history.confirm.today": "Den heutigen Verlauf löschen?",
      "history.confirm.week": "Den Verlauf dieser Woche löschen?",
      "history.confirm.all": "Den gesamten Verlauf löschen?",
      "bookmarks.title": "Lesezeichen",
      "bookmarks.close": "Lesezeichen schließen",
      "bookmarks.empty": "Noch keine Lesezeichen.",
      "downloads.title": "Downloads",
      "downloads.close": "Downloads schließen",
      "downloads.done": "Fertig",
      "adblock.kicker": "Datenschutz",
      "adblock.title": "Werbeblocker",
      "adblock.close": "Werbeblocker schließen",
      "adblock.description": "Erstelle eigene Blockierregeln, um Werbung, Pop-ups und bekannte Tracker zu entfernen. Füge pro Zeile eine Regel hinzu und wende sie sofort an.",
      "adblock.badge": "Eine Regel pro Zeile",
      "adblock.placeholder": "||ads.example.com^\n||tracker.example.net^\n! Kommentarzeilen beginnen mit !",
      "adblock.tip": "Tipp: Zeilen, die mit \"!\" beginnen, sind Kommentare. Inline-Kommentare nach einer Regel sind ebenfalls erlaubt.",
      "adblock.save": "Speichern und anwenden",
      "adblock.saved": "Gespeichert!",
      "settings.kicker": "Browser-Steuerung",
      "settings.title": "Einstellungen",
      "settings.close": "Einstellungsfenster schließen",
      "settings.heroKicker": "Personalisierung",
      "settings.heroTitle": "Mach Orion zu deinem Browser",
      "settings.heroBody": "Passe Aussehen und Verhalten deines Browsers an einem Ort an. Änderungen werden sofort übernommen.",
      "settings.themeTitle": "Design",
      "settings.themeSubtitle": "Wähle eine Akzentfarbe und passe das Layout an.",
      "settings.colorPicker": "Farbauswahl",
      "settings.colorPlaceholder": "Farbname oder Hex-Code",
      "settings.applyColor": "Farbe anwenden",
      "settings.discoMode": "Disco-Modus",
      "settings.stopDisco": "Disco stoppen",
      "settings.verticalTabs": "Vertikale Tabs",
      "settings.verticalTabsSub": "Tabs an der linken Seite andocken",
      "settings.showSeconds": "Sekunden anzeigen",
      "settings.showSecondsSub": "Sekunden in Zeit-Widgets anzeigen",
      "settings.languageTitle": "Sprache",
      "settings.languageSubtitle": "Wähle die Sprache für Orions Benutzeroberfläche.",
      "settings.searchTitle": "Suche",
      "settings.searchSubtitle": "Wähle die Suchmaschine für Klartextanfragen in der Adressleiste.",
      "settings.searchLabel": "Standardsuchmaschine",
      "settings.systemTitle": "System",
      "settings.systemSubtitle": "Prüfe deine Version und öffne die Erweiterungsverwaltung des Browsers.",
      "settings.checkUpdates": "Nach Updates suchen",
      "settings.openExtensions": "Erweiterungen öffnen",
      "updates.ready": "Bereit, nach Updates zu suchen.",
      "updates.checking": "Suche...",
      "updates.downloading": "Wird heruntergeladen...",
      "updates.restart": "Zum Aktualisieren neu starten",
      "updates.uptodate": "Aktuell",
      "updates.restarting": "Wird neu gestartet...",
      "modal.rename": "Umbenennen",
      "modal.cancel": "Abbrechen",
      "modal.save": "Speichern",
      "modal.bookmark": "Lesezeichen",
      "bookmark.bar": "Leiste",
      "bookmark.newTab": "Neuer Tab",
      "bookmark.both": "Beide",
      "download.loading": "Wird geladen...",
      "extension.pageTitle": "Erweiterungen",
      "extension.eyebrow": "Erweiterungen",
      "extension.header": "Installierte Erweiterungen verwalten",
      "extension.badge": "Entpackter Modus",
      "extension.loadTitle": "Entpackte Erweiterung laden",
      "extension.loadBody": "Um eine Erweiterung zu installieren, lade sie herunter, entpacke sie und füge unten den vollständigen Ordnerpfad ein.",
      "extension.loadExample": "(z. B. /Users/username/Downloads/my-extension)",
      "extension.pathPlaceholder": "absoluter/pfad/zum/erweiterungsordner",
      "extension.loadButton": "Erweiterung laden",
      "extension.installedTitle": "Installierte Erweiterungen",
      "extension.installedNote": "Aus lokalen Ordnern in diesem Browserprofil geladen.",
      "extension.remove": "Entfernen",
      "extension.removeConfirm": "Möchtest du diese Erweiterung wirklich entfernen?",
      "extension.empty": "Keine Erweiterungen installiert.",
      "extension.error": "Fehler beim Laden der Erweiterungen.",
      "extension.success": "Erweiterung erfolgreich geladen!",
      "extension.loadFailure": "Erweiterung konnte nicht geladen werden: {{error}}",
      "extension.invokeFailure": "Fehler beim Aufruf des Erweiterungs-Ladevorgangs: {{error}}",
      "extension.unknown": "Unbekannte Erweiterung",
      "extension.noDescription": "Keine Beschreibung vorhanden.",
      "newtab.pageTitle": "Neuer Tab",
      "newtab.searchPlaceholder": "Web durchsuchen",
      "newtab.removeShortcut": "{{name}} entfernen"
    }),
    ja: Object.freeze({
      "app.name": "Orion",
      "app.newTab": "新しいタブ",
      "app.loading": "読み込み中...",
      "address.placeholder": "検索または URL を入力",
      "find.placeholder": "ページ内検索...",
      "find.empty": "0/0",
      "toolbar.newTab": "新しいタブ",
      "toolbar.newIncognitoTab": "新しいシークレット タブ (Ctrl/Cmd+Shift+N)",
      "toolbar.closeOthers": "他を閉じる",
      "profile.addNew": "新しいプロフィールを追加",
      "profile.default": "デフォルト",
      "profile.named": "プロフィール {{index}}",
      "profile.incognito": "シークレット",
      "onboarding.kicker": "ようこそ",
      "onboarding.title": "言語を選択",
      "onboarding.subtitle": "Orion で使用する言語を選んでください。あとで設定から変更できます。",
      "onboarding.persist": "この選択はこの端末に保存され、通常はアプリを再インストールしても保持されます。",
      "history.title": "履歴",
      "history.close": "履歴パネルを閉じる",
      "history.remove": "履歴から削除",
      "history.range.hour": "1 時間",
      "history.range.today": "今日",
      "history.range.week": "今週",
      "history.range.all": "すべて削除",
      "history.confirm.hour": "直近 1 時間の履歴を削除しますか？",
      "history.confirm.today": "今日の履歴を削除しますか？",
      "history.confirm.week": "今週の履歴を削除しますか？",
      "history.confirm.all": "すべての履歴を削除しますか？",
      "bookmarks.title": "ブックマーク",
      "bookmarks.close": "ブックマーク パネルを閉じる",
      "bookmarks.empty": "まだブックマークがありません。",
      "downloads.title": "ダウンロード",
      "downloads.close": "ダウンロード パネルを閉じる",
      "downloads.done": "完了",
      "adblock.kicker": "プライバシー",
      "adblock.title": "広告ブロック",
      "adblock.close": "広告ブロック パネルを閉じる",
      "adblock.description": "広告、ポップアップ、既知のトラッカーを除去するためのカスタム ルールを作成します。1 行に 1 つのルールを追加するとすぐに適用されます。",
      "adblock.badge": "1 行に 1 ルール",
      "adblock.placeholder": "||ads.example.com^\n||tracker.example.net^\n! コメント行は ! で始まります",
      "adblock.tip": "ヒント: \"!\" で始まる行はコメントです。ルールの後ろにインライン コメントも書けます。",
      "adblock.save": "保存して適用",
      "adblock.saved": "保存しました",
      "settings.kicker": "ブラウザー操作",
      "settings.title": "設定",
      "settings.close": "設定パネルを閉じる",
      "settings.heroKicker": "カスタマイズ",
      "settings.heroTitle": "Orion を自分仕様に",
      "settings.heroBody": "ブラウザーの見た目と動作を 1 か所で調整できます。変更はすぐに反映されます。",
      "settings.themeTitle": "テーマ",
      "settings.themeSubtitle": "アクセント カラーを選び、レイアウトを調整します。",
      "settings.colorPicker": "カラーピッカー",
      "settings.colorPlaceholder": "色名または 16 進コード",
      "settings.applyColor": "色を適用",
      "settings.discoMode": "ディスコ モード",
      "settings.stopDisco": "ディスコを停止",
      "settings.verticalTabs": "縦型タブ",
      "settings.verticalTabsSub": "タブを左側に固定する",
      "settings.showSeconds": "秒を表示",
      "settings.showSecondsSub": "時刻ウィジェットに秒を表示する",
      "settings.languageTitle": "言語",
      "settings.languageSubtitle": "Orion のインターフェースで使う言語を選択します。",
      "settings.searchTitle": "検索",
      "settings.searchSubtitle": "アドレスバーで通常の文字列を検索するときの検索エンジンを選びます。",
      "settings.searchLabel": "既定の検索エンジン",
      "settings.systemTitle": "システム",
      "settings.systemSubtitle": "バージョンを確認し、拡張機能の管理を開きます。",
      "settings.checkUpdates": "アップデートを確認",
      "settings.openExtensions": "拡張機能を開く",
      "updates.ready": "アップデートを確認する準備ができました。",
      "updates.checking": "確認中...",
      "updates.downloading": "ダウンロード中...",
      "updates.restart": "再起動して更新",
      "updates.uptodate": "最新です",
      "updates.restarting": "再起動中...",
      "modal.rename": "名前を変更",
      "modal.cancel": "キャンセル",
      "modal.save": "保存",
      "modal.bookmark": "ブックマーク",
      "bookmark.bar": "バー",
      "bookmark.newTab": "新しいタブ",
      "bookmark.both": "両方",
      "download.loading": "読み込み中...",
      "extension.pageTitle": "拡張機能",
      "extension.eyebrow": "拡張機能",
      "extension.header": "インストール済み拡張機能を管理",
      "extension.badge": "展開モード",
      "extension.loadTitle": "展開済み拡張機能を読み込む",
      "extension.loadBody": "拡張機能をインストールするには、ダウンロードして展開し、下にフォルダーの完全なパスを貼り付けてください。",
      "extension.loadExample": "(例: /Users/username/Downloads/my-extension)",
      "extension.pathPlaceholder": "拡張機能フォルダーへの絶対パス",
      "extension.loadButton": "拡張機能を読み込む",
      "extension.installedTitle": "インストール済み拡張機能",
      "extension.installedNote": "このブラウザー プロフィールのローカル フォルダーから読み込まれています。",
      "extension.remove": "削除",
      "extension.removeConfirm": "この拡張機能を削除してもよろしいですか？",
      "extension.empty": "拡張機能はまだありません。",
      "extension.error": "拡張機能の読み込み中にエラーが発生しました。",
      "extension.success": "拡張機能を読み込みました。",
      "extension.loadFailure": "拡張機能の読み込みに失敗しました: {{error}}",
      "extension.invokeFailure": "拡張機能の読み込み呼び出しでエラーが発生しました: {{error}}",
      "extension.unknown": "不明な拡張機能",
      "extension.noDescription": "説明はありません。",
      "newtab.pageTitle": "新しいタブ",
      "newtab.searchPlaceholder": "ウェブを検索",
      "newtab.removeShortcut": "{{name}} を削除"
    })
  });

  function sanitizeLocale(locale) {
    return SUPPORTED_LOCALES.includes(locale) ? locale : null;
  }

  function resolveLocale(locale, fallback = DEFAULT_LOCALE) {
    return sanitizeLocale(locale) || fallback;
  }

  function getIntlLocale(locale) {
    return INTL_LOCALES[resolveLocale(locale)] || INTL_LOCALES[DEFAULT_LOCALE];
  }

  function getMessages(locale) {
    return TRANSLATIONS[resolveLocale(locale)] || TRANSLATIONS[DEFAULT_LOCALE];
  }

  function interpolate(template, vars = {}) {
    return String(template).replace(/\{\{(\w+)\}\}/g, (_, key) => {
      return Object.prototype.hasOwnProperty.call(vars, key) ? String(vars[key]) : "";
    });
  }

  function t(locale, key, vars = {}) {
    const messages = getMessages(locale);
    const fallback = TRANSLATIONS[DEFAULT_LOCALE];
    const template = messages[key] != null ? messages[key] : fallback[key];
    if (template == null) return key;
    return interpolate(template, vars);
  }

  function getLanguageOptions() {
    return LANGUAGE_OPTIONS.slice();
  }

  function getProfileName(locale, index) {
    if (index === 0) return t(locale, "profile.default");
    return t(locale, "profile.named", { index });
  }

  function getIncognitoProfileName(locale) {
    return t(locale, "profile.incognito");
  }

  function isGeneratedProfileName(name, index) {
    if (!name) return false;
    return SUPPORTED_LOCALES.some((locale) => {
      return name === getProfileName(locale, index) || name === getIncognitoProfileName(locale);
    });
  }

  return {
    DEFAULT_LOCALE,
    INTL_LOCALES,
    SUPPORTED_LOCALES,
    TRANSLATIONS,
    getIntlLocale,
    getIncognitoProfileName,
    getLanguageOptions,
    getMessages,
    getProfileName,
    isGeneratedProfileName,
    resolveLocale,
    sanitizeLocale,
    t
  };
});
