(function (root, factory) {
  if (typeof module === "object" && module.exports) {
    module.exports = factory();
    return;
  }
  root.OrionLocalization = factory();
})(typeof globalThis !== "undefined" ? globalThis : this, () => {
  const SUPPORTED_LOCALES = Object.freeze(["en", "fr", "de", "ja"]);
  const DEFAULT_LOCALE = "en";
  const INTL_LOCALES = Object.freeze({
    en: "en-US",
    fr: "fr-FR",
    de: "de-DE",
    ja: "ja-JP"
  });

  const LANGUAGE_OPTIONS = Object.freeze([
    { locale: "en", label: "English" },
    { locale: "fr", label: "Français" },
    { locale: "de", label: "Deutsch" },
    { locale: "ja", label: "日本語" }
  ]);
  const UI_PLATFORM_EXTENSION_PATHS = Object.freeze({
    windows: "C:\\Users\\username\\Downloads\\my-extension",
    mac: "/Users/username/Downloads/my-extension",
    linux: "/home/username/Downloads/my-extension"
  });
  const UI_PLATFORM_PRIMARY_MODIFIERS = Object.freeze({
    windows: Object.freeze({
      default: "Ctrl",
      de: "Strg"
    }),
    mac: Object.freeze({
      default: "Cmd"
    }),
    linux: Object.freeze({
      default: "Ctrl",
      de: "Strg"
    })
  });

  const TRANSLATIONS = Object.freeze({
    en: Object.freeze({
      "app.name": "Orion",
      "app.newTab": "New Tab",
      "app.loading": "Loading...",
      "address.placeholder": "Search or enter URL",
      "find.placeholder": "Find...",
      "find.empty": "0/0",
      "toolbar.newTab": "New Tab",
      "toolbar.tabGroups": "Tab Groups",
      "toolbar.newIncognitoTab": "New Incognito Tab ({{primaryModifierLabel}}+Shift+N)",
      "toolbar.closeOthers": "Close Others",
      "toolbar.extensionsMenuButton": "Extensions menu",
      "toolbar.extensionsMenuTitle": "Extensions",
      "toolbar.extensionsMenuNote": "Pinned extensions stay in the toolbar.",
      "toolbar.extensionsPinned": "Shown in toolbar",
      "toolbar.extensionsHidden": "Hidden from toolbar",
      "toolbar.pinExtension": "Pin",
      "toolbar.unpinExtension": "Unpin",
      "aiSummary.button": "AI Summary",
      "aiSummary.kicker": "On-device AI",
      "aiSummary.title": "AI Summary",
      "aiSummary.close": "Close AI summary panel",
      "aiSummary.loading": "Summarizing this page on device...",
      "aiSummary.unavailable": "Orion could not summarize this page.",
      "aiSummary.untitled": "Untitled page",
      "aiSummary.localOnly": "On device",
      "aiSummary.readingTime": "{{minutes}} min read",
      "profile.addNew": "Add New Profile",
      "profile.default": "Default",
      "profile.named": "Profile {{index}}",
      "profile.incognito": "Incognito",
      "onboarding.kicker": "Welcome",
      "onboarding.title": "Choose your language",
      "onboarding.subtitle": "Pick the language Orion should use. You can change it later in Settings.",
      "onboarding.persist": "Your choice is saved for this device and usually survives reinstalling the app.",
      "history.title": "History",
      "history.close": "Close history panel",
      "history.remove": "Remove from history",
      "history.range.hour": "Hour",
      "history.range.today": "Today",
      "history.range.week": "Week",
      "history.range.all": "Clear All",
      "history.confirm.hour": "Clear the last hour of history?",
      "history.confirm.today": "Clear today's history?",
      "history.confirm.week": "Clear this week's history?",
      "history.confirm.all": "Clear all history?",
      "bookmarks.title": "Bookmarks",
      "bookmarks.close": "Close bookmarks panel",
      "bookmarks.empty": "No bookmarks yet.",
      "downloads.title": "Downloads",
      "downloads.close": "Close downloads panel",
      "downloads.done": "Done",
      "managedExtension.kicker": "Required protection",
      "managedExtension.installingTitle": "Installing uBlock Origin Lite",
      "managedExtension.installingBody": "Orion is preparing mandatory ad and tracker protection for this browser profile.",
      "managedExtension.errorTitle": "uBlock Origin Lite is required",
      "managedExtension.errorBody": "Orion could not install the required extension from the Chrome Web Store. Check your connection and retry.",
      "managedExtension.retry": "Retry installation",
      "settings.kicker": "Browser Controls",
      "settings.title": "Settings",
      "settings.close": "Close settings panel",
      "settings.heroKicker": "Personalization",
      "settings.heroTitle": "Make Orion yours",
      "settings.heroBody": "Customize the look and behavior of your browser in one place. Changes apply immediately.",
      "settings.themeTitle": "Theme",
      "settings.themeSubtitle": "Pick an accent and tune layout preferences.",
      "settings.colorPicker": "Color Picker",
      "settings.colorPlaceholder": "Color name or hex",
      "settings.applyColor": "Apply Color",
      "settings.discoMode": "Disco Mode",
      "settings.stopDisco": "Stop Disco",
      "settings.verticalTabs": "Vertical Tabs",
      "settings.verticalTabsSub": "Dock tabs on the left side",
      "settings.showSeconds": "Show Seconds",
      "settings.showSecondsSub": "Display seconds in time widgets",
      "settings.languageTitle": "Language",
      "settings.languageSubtitle": "Choose the language used for Orion's interface.",
      "settings.searchTitle": "Search",
      "settings.searchSubtitle": "Choose the engine used by the address bar for plain text queries.",
      "settings.searchLabel": "Default search engine",
      "settings.privacyTitle": "Privacy",
      "settings.privacySubtitle": "Harden web requests and reduce fingerprinting across browser sessions.",
      "settings.httpsOnly": "HTTPS-Only Mode",
      "settings.httpsOnlySub": "Upgrade insecure HTTP navigations to HTTPS and block plaintext fallback.",
      "settings.antiFingerprinting": "Anti-Fingerprinting",
      "settings.antiFingerprintingSub": "Normalize browser signals like language, hardware details, timezone, and graphics identifiers.",
      "settings.doh": "DNS-over-HTTPS",
      "settings.dohSub": "Use Cloudflare in strict secure-DNS mode for supported name resolution.",
      "settings.performanceTitle": "Performance",
      "settings.performanceSubtitle": "Automatically cap Orion at half of this computer's RAM.",
      "settings.ramAutomaticSubtitle": "Automatically cap Orion at half of this computer's RAM.",
      "settings.ramCustomSubtitle": "Set a custom RAM limit for Orion.",
      "settings.ramOffSubtitle": "Turn off Orion's RAM limit.",
      "settings.ramAutomaticSubtitle": "Automatically cap Orion at half of this computer's RAM.",
      "settings.ramCustomSubtitle": "Set a custom RAM limit for Orion.",
      "settings.ramOffSubtitle": "Turn off Orion's RAM limit.",
      "settings.ramAutomaticSubtitle": "Automatically cap Orion at half of this computer's RAM.",
      "settings.ramCustomSubtitle": "Set a custom RAM limit for Orion.",
      "settings.ramOffSubtitle": "Turn off Orion's RAM limit.",
      "settings.ramAutomaticSubtitle": "Automatically cap Orion at half of this computer's RAM.",
      "settings.ramCustomSubtitle": "Set a custom RAM limit for Orion.",
      "settings.ramOffSubtitle": "Turn off Orion's RAM limit.",
      "settings.ramLimitLabel": "RAM limit",
      "settings.ramOff": "Off",
      "settings.ramAutomatic": "Automatic ({{limit}} GB)",
      "settings.ramAutomaticUnavailable": "Automatic (unavailable)",
      "settings.ramCustom": "Custom",
      "settings.ramCustomLabel": "Custom limit",
      "settings.ramUsageLabel": "Current usage",
      "settings.ramWarning": "When Orion is over the limit, the background tabs with the highest observed memory use reload when reopened. Scroll position, navigation history, form entries, and other unsaved page state may be lost. Active and audible tabs are protected.",
      "settings.ramUnavailable": "Usage unavailable",
      "settings.ramUsageWithLimit": "{{used}} MB / {{limit}} GB",
      "settings.ramUsageNoLimit": "{{used}} MB • Off",
      "settings.ramUnloadedTab": "{{count}} tab unloaded",
      "settings.ramUnloadedTabs": "{{count}} tabs unloaded",
      "settings.systemTitle": "System",
      "settings.systemSubtitle": "Check your version and open browser extension management.",
      "settings.checkUpdates": "Check for Updates",
      "settings.openExtensions": "Open Extensions",
      "settings.aiTitle": "On-device AI",
      "settings.aiSubtitle": "Manage the local language model used for page summaries.",
      "settings.aiModelId": "Model",
      "settings.aiStatusLabel": "Status",
      "settings.removeAiModel": "Remove",
      "settings.redownloadAiModel": "Redownload",
      "settings.aiReady": "Ready",
      "settings.aiMissing": "Not downloaded",
      "settings.aiError": "Unavailable",
      "aiModel.status.missing": "Not downloaded",
      "aiModel.status.downloading": "Downloading ({{progress}}%)",
      "aiModel.status.ready": "Ready",
      "aiModel.status.error": "Error: {{error}}",
      "aiModel.status.cancelling": "Cancelling...",
      "aiSummary.downloading": "Downloading model...",
      "aiSummary.generating": "Generating summary...",
      "aiSummary.cancelled": "Summary cancelled",
      "aiSummary.retry": "Retry",
      "aiSummary.cancel": "Cancel",
      "aiSummary.fallback": "Fallback Summary",
      "aiSummary.contextMenu": "Summarize this page",
      "aiSummary.chatTitle": "Chat with this page",
      "aiSummary.chatPlaceholder": "Ask a question about this page",
      "aiSummary.chatSend": "Ask",
      "aiSummary.chatThinking": "Thinking...",
      "aiSummary.chatUnavailable": "I could not answer from this page.",
      "privacy.httpsOnlyErrorTitle": "Secure connection required",
      "privacy.httpsOnlyErrorBody": "Orion upgraded this request to HTTPS, but the secure version of the site could not be loaded.",
      "privacy.httpsOnlyErrorDetail": "HTTP fallback is disabled while HTTPS-Only Mode is enabled.",
      "updates.ready": "Ready to check for updates.",
      "updates.checking": "Checking...",
      "updates.downloading": "Downloading...",
      "updates.restart": "Restart to Update",
      "updates.uptodate": "Up to Date",
      "updates.restarting": "Restarting...",
      "modal.rename": "Rename",
      "modal.cancel": "Cancel",
      "modal.save": "Save",
      "modal.bookmark": "Bookmark",
      "bookmark.bar": "Bar",
      "bookmark.newTab": "New Tab",
      "bookmark.both": "Both",
      "download.loading": "Loading...",
      "extension.pageTitle": "Extensions",
      "extension.eyebrow": "Extensions",
      "extension.header": "Manage Installed Extensions",
      "extension.badge": "Web Store Ready",
      "extension.loadTitle": "Load Unpacked Extension",
      "extension.loadBody": "Install from the Chrome Web Store, or load a trusted unpacked extension folder for local development.",
      "extension.loadExample": "(e.g., {{extensionPathExample}})",
      "extension.pathPlaceholder": "{{extensionPathPlaceholder}}",
      "extension.loadButton": "Load Extension",
      "extension.installedTitle": "Installed Extensions",
      "extension.installedNote": "Installed from the Chrome Web Store or local folders in this browser profile.",
      "extension.remove": "Remove",
      "extension.removeConfirm": "Are you sure you want to remove this extension?",
      "extension.empty": "No extensions installed.",
      "extension.error": "Error loading extensions.",
      "extension.success": "Extension loaded successfully!",
      "extension.loadFailure": "Failed to load extension: {{error}}",
      "extension.invokeFailure": "Error invoking extension load: {{error}}",
      "extension.unknown": "Unknown extension",
      "extension.noDescription": "No description provided.",
      "extension.openWebStore": "Open Chrome Web Store",
      "extension.updateButton": "Check Extension Updates",
      "extension.updateSuccess": "Extension update check complete.",
      "extension.updateFailure": "Failed to update extensions: {{error}}",
      "extension.webStoreFailure": "Failed to open Chrome Web Store: {{error}}",
      "extension.sourceWebStore": "Chrome Web Store",
      "extension.sourceUnpacked": "Unpacked",
      "extension.managed": "Managed by Orion",
      "extension.unknownManifest": "Manifest unknown",
      "newtab.pageTitle": "New Tab",
      "newtab.searchPlaceholder": "Search the web",
      "newtab.removeShortcut": "Remove {{name}}",
      "reader.title": "Reader",
      "reader.modeLabel": "Reader mode",
      "reader.loadingArticle": "Loading article",
      "reader.enterMode": "Reader Mode",
      "reader.exitMode": "Exit Reader Mode",
      "reader.backToPage": "Back to page",
      "reader.theme": "Theme",
      "reader.fontSize": "Font size",
      "reader.themeSepia": "Sepia",
      "reader.themeLight": "Light",
      "reader.themeNight": "Night",
      "reader.openCanonicalSource": "Open canonical source",
      "reader.updated": "Updated {{value}}",
      "reader.unavailable": "Reader unavailable",
      "reader.unavailableState": "Reader mode is unavailable for this page.",
      "reader.unavailableTitle": "This page could not be converted",
      "reader.unavailableSubtitle": "Orion could not confidently extract a readable article from this page.",
      "reader.dataNotReady": "Reader data is not ready yet.",
      "reader.loadFailed": "Orion could not load reader mode for this page.",
      "reader.untitledArticle": "Untitled article"
    }),
    fr: Object.freeze({
      "app.name": "Orion",
      "app.newTab": "Nouvel onglet",
      "app.loading": "Chargement...",
      "address.placeholder": "Rechercher ou saisir une URL",
      "find.placeholder": "Rechercher...",
      "find.empty": "0/0",
      "toolbar.newTab": "Nouvel onglet",
      "toolbar.tabGroups": "Groupes d'onglets",
      "toolbar.newIncognitoTab": "Nouvel onglet privé ({{primaryModifierLabel}}+Maj+N)",
      "toolbar.closeOthers": "Fermer les autres",
      "aiSummary.button": "Résumé IA",
      "aiSummary.kicker": "IA sur l'appareil",
      "aiSummary.title": "Résumé IA",
      "aiSummary.close": "Fermer le panneau de résumé IA",
      "aiSummary.loading": "Résumé de cette page sur l'appareil...",
      "aiSummary.unavailable": "Orion n'a pas pu résumer cette page.",
      "aiSummary.untitled": "Page sans titre",
      "aiSummary.localOnly": "Sur l'appareil",
      "aiSummary.readingTime": "{{minutes}} min de lecture",
      "profile.addNew": "Ajouter un profil",
      "profile.default": "Par défaut",
      "profile.named": "Profil {{index}}",
      "profile.incognito": "Navigation privée",
      "onboarding.kicker": "Bienvenue",
      "onboarding.title": "Choisissez votre langue",
      "onboarding.subtitle": "Choisissez la langue utilisée par Orion. Vous pourrez la modifier plus tard dans les réglages.",
      "onboarding.persist": "Votre choix est enregistré pour cet appareil et survit généralement à une réinstallation de l'application.",
      "history.title": "Historique",
      "history.close": "Fermer le panneau d'historique",
      "history.remove": "Retirer de l'historique",
      "history.range.hour": "Heure",
      "history.range.today": "Aujourd'hui",
      "history.range.week": "Semaine",
      "history.range.all": "Tout effacer",
      "history.confirm.hour": "Effacer l'historique de la dernière heure ?",
      "history.confirm.today": "Effacer l'historique d'aujourd'hui ?",
      "history.confirm.week": "Effacer l'historique de cette semaine ?",
      "history.confirm.all": "Effacer tout l'historique ?",
      "bookmarks.title": "Favoris",
      "bookmarks.close": "Fermer le panneau des favoris",
      "bookmarks.empty": "Aucun favori pour le moment.",
      "downloads.title": "Téléchargements",
      "downloads.close": "Fermer le panneau des téléchargements",
      "downloads.done": "Terminé",
      "managedExtension.kicker": "Protection requise",
      "managedExtension.installingTitle": "Installation de uBlock Origin Lite",
      "managedExtension.installingBody": "Orion prépare la protection obligatoire contre les publicités et les traqueurs pour ce profil.",
      "managedExtension.errorTitle": "uBlock Origin Lite est requis",
      "managedExtension.errorBody": "Orion n’a pas pu installer l’extension requise depuis le Chrome Web Store. Vérifiez votre connexion et réessayez.",
      "managedExtension.retry": "Réessayer l’installation",
      "settings.kicker": "Contrôles du navigateur",
      "settings.title": "Réglages",
      "settings.close": "Fermer le panneau des réglages",
      "settings.heroKicker": "Personnalisation",
      "settings.heroTitle": "Faites d'Orion le vôtre",
      "settings.heroBody": "Personnalisez l'apparence et le comportement de votre navigateur depuis un seul endroit. Les changements sont appliqués immédiatement.",
      "settings.themeTitle": "Thème",
      "settings.themeSubtitle": "Choisissez une couleur d'accentuation et ajustez la disposition.",
      "settings.colorPicker": "Sélecteur de couleur",
      "settings.colorPlaceholder": "Nom de couleur ou code hexadécimal",
      "settings.applyColor": "Appliquer la couleur",
      "settings.discoMode": "Mode disco",
      "settings.stopDisco": "Arrêter le disco",
      "settings.verticalTabs": "Onglets verticaux",
      "settings.verticalTabsSub": "Afficher les onglets sur le côté gauche",
      "settings.showSeconds": "Afficher les secondes",
      "settings.showSecondsSub": "Afficher les secondes dans les widgets d'heure",
      "settings.languageTitle": "Langue",
      "settings.languageSubtitle": "Choisissez la langue utilisée par l'interface d'Orion.",
      "settings.searchTitle": "Recherche",
      "settings.searchSubtitle": "Choisissez le moteur utilisé par la barre d'adresse pour les requêtes en texte brut.",
      "settings.searchLabel": "Moteur de recherche par défaut",
      "settings.privacyTitle": "Confidentialité",
      "settings.privacySubtitle": "Renforcez les requêtes web et réduisez l'empreinte numérique dans toutes les sessions du navigateur.",
      "settings.httpsOnly": "Mode HTTPS uniquement",
      "settings.httpsOnlySub": "Met à niveau les navigations HTTP non sécurisées vers HTTPS et bloque le retour au texte brut.",
      "settings.antiFingerprinting": "Anti-empreinte numérique",
      "settings.antiFingerprintingSub": "Normalise la langue, le matériel, le fuseau horaire et les identifiants graphiques du navigateur.",
      "settings.doh": "DNS sur HTTPS",
      "settings.dohSub": "Utilise Cloudflare en mode DNS sécurisé strict pour la résolution prise en charge.",
      "settings.performanceTitle": "Performances",
      "settings.performanceSubtitle": "Limitez automatiquement Orion à la moitié de la mémoire vive de cet ordinateur.",
      "settings.ramLimitLabel": "Limite de mémoire vive",
      "settings.ramOff": "Désactivée",
      "settings.ramAutomatic": "Automatique ({{limit}} Go)",
      "settings.ramAutomaticUnavailable": "Automatique (indisponible)",
      "settings.ramCustom": "Personnalisé",
      "settings.ramCustomLabel": "Limite personnalisée",
      "settings.ramUsageLabel": "Utilisation actuelle",
      "settings.ramWarning": "Quand Orion dépasse la limite, les onglets d'arrière-plan dont l'utilisation de mémoire observée est la plus élevée sont rechargés à leur réouverture. La position de défilement, l'historique de navigation, les formulaires et les autres données non enregistrées peuvent être perdus. Les onglets actifs et audibles sont protégés.",
      "settings.ramUnavailable": "Utilisation indisponible",
      "settings.ramUsageWithLimit": "{{used}} Mo / {{limit}} Go",
      "settings.ramUsageNoLimit": "{{used}} Mo • Désactivée",
      "settings.ramUnloadedTab": "{{count}} onglet déchargé",
      "settings.ramUnloadedTabs": "{{count}} onglets déchargés",
      "settings.systemTitle": "Système",
      "settings.systemSubtitle": "Vérifiez votre version et ouvrez la gestion des extensions du navigateur.",
      "settings.checkUpdates": "Rechercher des mises à jour",
      "settings.openExtensions": "Ouvrir les extensions",
      "settings.aiTitle": "IA locale",
      "settings.aiSubtitle": "Gérer le modèle de langue local utilisé pour les résumés.",
      "settings.aiModelId": "Modèle",
      "settings.aiStatusLabel": "Statut",
      "settings.removeAiModel": "Supprimer",
      "settings.redownloadAiModel": "Télécharger à nouveau",
      "settings.aiReady": "Prêt",
      "settings.aiMissing": "Non téléchargé",
      "settings.aiError": "Indisponible",
      "aiModel.status.missing": "Non téléchargé",
      "aiModel.status.downloading": "Téléchargement ({{progress}}%)",
      "aiModel.status.ready": "Prêt",
      "aiModel.status.error": "Erreur: {{error}}",
      "aiModel.status.cancelling": "Annulation...",
      "aiSummary.downloading": "Téléchargement du modèle...",
      "aiSummary.generating": "Génération du résumé...",
      "aiSummary.cancelled": "Résumé annulé",
      "aiSummary.retry": "Réessayer",
      "aiSummary.cancel": "Annuler",
      "aiSummary.fallback": "Résumé de secours",
      "aiSummary.contextMenu": "Résumer cette page",
      "aiSummary.chatTitle": "Discuter avec cette page",
      "aiSummary.chatPlaceholder": "Posez une question sur cette page",
      "aiSummary.chatSend": "Demander",
      "aiSummary.chatThinking": "Réflexion...",
      "aiSummary.chatUnavailable": "Impossible de répondre à partir de cette page.",
      "privacy.httpsOnlyErrorTitle": "Connexion sécurisée requise",
      "privacy.httpsOnlyErrorBody": "Orion a mis à niveau cette requête vers HTTPS, mais la version sécurisée du site n'a pas pu être chargée.",
      "privacy.httpsOnlyErrorDetail": "Le retour vers HTTP est désactivé tant que le mode HTTPS uniquement est actif.",
      "updates.ready": "Prêt à rechercher des mises à jour.",
      "updates.checking": "Recherche...",
      "updates.downloading": "Téléchargement...",
      "updates.restart": "Redémarrer pour mettre à jour",
      "updates.uptodate": "À jour",
      "updates.restarting": "Redémarrage...",
      "modal.rename": "Renommer",
      "modal.cancel": "Annuler",
      "modal.save": "Enregistrer",
      "modal.bookmark": "Favori",
      "bookmark.bar": "Barre",
      "bookmark.newTab": "Nouvel onglet",
      "bookmark.both": "Les deux",
      "download.loading": "Chargement...",
      "extension.pageTitle": "Extensions",
      "extension.eyebrow": "Extensions",
      "extension.header": "Gérer les extensions installées",
      "extension.badge": "Web Store prêt",
      "extension.loadTitle": "Charger une extension non empaquetée",
      "extension.loadBody": "Installez depuis le Chrome Web Store ou chargez un dossier d'extension non empaquetée de confiance pour le développement local.",
      "extension.loadExample": "(par ex. {{extensionPathExample}})",
      "extension.pathPlaceholder": "{{extensionPathPlaceholder}}",
      "extension.loadButton": "Charger l'extension",
      "extension.installedTitle": "Extensions installées",
      "extension.installedNote": "Installées depuis le Chrome Web Store ou des dossiers locaux dans ce profil du navigateur.",
      "extension.remove": "Supprimer",
      "extension.removeConfirm": "Voulez-vous vraiment supprimer cette extension ?",
      "extension.empty": "Aucune extension installée.",
      "extension.error": "Erreur lors du chargement des extensions.",
      "extension.success": "Extension chargée avec succès !",
      "extension.loadFailure": "Échec du chargement de l'extension : {{error}}",
      "extension.invokeFailure": "Erreur lors de l'appel du chargement de l'extension : {{error}}",
      "extension.unknown": "Extension inconnue",
      "extension.noDescription": "Aucune description fournie.",
      "extension.openWebStore": "Ouvrir le Chrome Web Store",
      "extension.updateButton": "Rechercher des mises à jour",
      "extension.updateSuccess": "Recherche de mises à jour des extensions terminée.",
      "extension.updateFailure": "Échec de la mise à jour des extensions : {{error}}",
      "extension.webStoreFailure": "Impossible d'ouvrir le Chrome Web Store : {{error}}",
      "extension.sourceWebStore": "Chrome Web Store",
      "extension.sourceUnpacked": "Non empaquetée",
      "extension.managed": "Gérée par Orion",
      "extension.unknownManifest": "Manifeste inconnu",
      "newtab.pageTitle": "Nouvel onglet",
      "newtab.searchPlaceholder": "Rechercher sur le Web",
      "newtab.removeShortcut": "Retirer {{name}}",
      "reader.title": "Lecteur",
      "reader.modeLabel": "Mode lecture",
      "reader.loadingArticle": "Chargement de l'article",
      "reader.enterMode": "Mode lecture",
      "reader.exitMode": "Quitter le mode lecture",
      "reader.backToPage": "Retour à la page",
      "reader.theme": "Thème",
      "reader.fontSize": "Taille du texte",
      "reader.themeSepia": "Sépia",
      "reader.themeLight": "Clair",
      "reader.themeNight": "Nuit",
      "reader.openCanonicalSource": "Ouvrir la source canonique",
      "reader.updated": "Mis à jour {{value}}",
      "reader.unavailable": "Lecture indisponible",
      "reader.unavailableState": "Le mode lecture n'est pas disponible pour cette page.",
      "reader.unavailableTitle": "Cette page n'a pas pu être convertie",
      "reader.unavailableSubtitle": "Orion n'a pas pu extraire avec suffisamment de confiance un article lisible de cette page.",
      "reader.dataNotReady": "Les données du mode lecture ne sont pas encore prêtes.",
      "reader.loadFailed": "Orion n'a pas pu charger le mode lecture pour cette page.",
      "reader.untitledArticle": "Article sans titre"
    }),
    de: Object.freeze({
      "app.name": "Orion",
      "app.newTab": "Neuer Tab",
      "app.loading": "Wird geladen...",
      "address.placeholder": "Suchen oder URL eingeben",
      "find.placeholder": "Suchen...",
      "find.empty": "0/0",
      "toolbar.newTab": "Neuer Tab",
      "toolbar.tabGroups": "Tabgruppen",
      "toolbar.newIncognitoTab": "Neuer Inkognito-Tab ({{primaryModifierLabel}}+Umschalt+N)",
      "toolbar.closeOthers": "Andere schließen",
      "aiSummary.button": "KI-Zusammenfassung",
      "aiSummary.kicker": "KI auf dem Gerät",
      "aiSummary.title": "KI-Zusammenfassung",
      "aiSummary.close": "KI-Zusammenfassung schließen",
      "aiSummary.loading": "Diese Seite wird auf dem Gerät zusammengefasst...",
      "aiSummary.unavailable": "Orion konnte diese Seite nicht zusammenfassen.",
      "aiSummary.untitled": "Unbenannte Seite",
      "aiSummary.localOnly": "Auf dem Gerät",
      "aiSummary.readingTime": "{{minutes}} Min. Lesezeit",
      "profile.addNew": "Neues Profil hinzufügen",
      "profile.default": "Standard",
      "profile.named": "Profil {{index}}",
      "profile.incognito": "Inkognito",
      "onboarding.kicker": "Willkommen",
      "onboarding.title": "Sprache auswählen",
      "onboarding.subtitle": "Wähle die Sprache, die Orion verwenden soll. Du kannst sie später in den Einstellungen ändern.",
      "onboarding.persist": "Deine Auswahl wird für dieses Gerät gespeichert und bleibt bei einer Neuinstallation normalerweise erhalten.",
      "history.title": "Verlauf",
      "history.close": "Verlauf schließen",
      "history.remove": "Aus dem Verlauf entfernen",
      "history.range.hour": "Stunde",
      "history.range.today": "Heute",
      "history.range.week": "Woche",
      "history.range.all": "Alles löschen",
      "history.confirm.hour": "Den Verlauf der letzten Stunde löschen?",
      "history.confirm.today": "Den heutigen Verlauf löschen?",
      "history.confirm.week": "Den Verlauf dieser Woche löschen?",
      "history.confirm.all": "Den gesamten Verlauf löschen?",
      "bookmarks.title": "Lesezeichen",
      "bookmarks.close": "Lesezeichen schließen",
      "bookmarks.empty": "Noch keine Lesezeichen.",
      "downloads.title": "Downloads",
      "downloads.close": "Downloads schließen",
      "downloads.done": "Fertig",
      "managedExtension.kicker": "Erforderlicher Schutz",
      "managedExtension.installingTitle": "uBlock Origin Lite wird installiert",
      "managedExtension.installingBody": "Orion richtet den verpflichtenden Werbe- und Tracking-Schutz für dieses Browserprofil ein.",
      "managedExtension.errorTitle": "uBlock Origin Lite ist erforderlich",
      "managedExtension.errorBody": "Orion konnte die erforderliche Erweiterung nicht aus dem Chrome Web Store installieren. Prüfe die Verbindung und versuche es erneut.",
      "managedExtension.retry": "Installation erneut versuchen",
      "settings.kicker": "Browser-Steuerung",
      "settings.title": "Einstellungen",
      "settings.close": "Einstellungsfenster schließen",
      "settings.heroKicker": "Personalisierung",
      "settings.heroTitle": "Mach Orion zu deinem Browser",
      "settings.heroBody": "Passe Aussehen und Verhalten deines Browsers an einem Ort an. Änderungen werden sofort übernommen.",
      "settings.themeTitle": "Design",
      "settings.themeSubtitle": "Wähle eine Akzentfarbe und passe das Layout an.",
      "settings.colorPicker": "Farbauswahl",
      "settings.colorPlaceholder": "Farbname oder Hex-Code",
      "settings.applyColor": "Farbe anwenden",
      "settings.discoMode": "Disco-Modus",
      "settings.stopDisco": "Disco stoppen",
      "settings.verticalTabs": "Vertikale Tabs",
      "settings.verticalTabsSub": "Tabs an der linken Seite andocken",
      "settings.showSeconds": "Sekunden anzeigen",
      "settings.showSecondsSub": "Sekunden in Zeit-Widgets anzeigen",
      "settings.languageTitle": "Sprache",
      "settings.languageSubtitle": "Wähle die Sprache für Orions Benutzeroberfläche.",
      "settings.searchTitle": "Suche",
      "settings.searchSubtitle": "Wähle die Suchmaschine für Klartextanfragen in der Adressleiste.",
      "settings.searchLabel": "Standardsuchmaschine",
      "settings.privacyTitle": "Datenschutz",
      "settings.privacySubtitle": "Härtet Webanfragen ab und reduziert Fingerprinting in allen Browsersitzungen.",
      "settings.httpsOnly": "Nur-HTTPS-Modus",
      "settings.httpsOnlySub": "Rüstet unsichere HTTP-Navigationen auf HTTPS um und blockiert die Rückkehr zu Klartext.",
      "settings.antiFingerprinting": "Anti-Fingerprinting",
      "settings.antiFingerprintingSub": "Vereinheitlicht Sprach-, Hardware-, Zeitzonen- und Grafikmerkmale des Browsers.",
      "settings.doh": "DNS-over-HTTPS",
      "settings.dohSub": "Verwendet Cloudflare im strikten Secure-DNS-Modus für unterstützte Namensauflösung.",
      "settings.performanceTitle": "Leistung",
      "settings.performanceSubtitle": "Begrenze Orion automatisch auf die Hälfte des Arbeitsspeichers dieses Computers.",
      "settings.ramLimitLabel": "Arbeitsspeicherlimit",
      "settings.ramOff": "Aus",
      "settings.ramAutomatic": "Automatisch ({{limit}} GB)",
      "settings.ramAutomaticUnavailable": "Automatisch (nicht verfügbar)",
      "settings.ramCustom": "Benutzerdefiniert",
      "settings.ramCustomLabel": "Benutzerdefiniertes Limit",
      "settings.ramUsageLabel": "Aktuelle Nutzung",
      "settings.ramWarning": "Wenn Orion das Limit überschreitet, werden die Hintergrund-Tabs mit der höchsten beobachteten Speichernutzung beim erneuten Öffnen neu geladen. Scrollposition, Navigationsverlauf, Formulareinträge und andere nicht gespeicherte Seitendaten können verloren gehen. Aktive und hörbare Tabs sind geschützt.",
      "settings.ramUnavailable": "Nutzung nicht verfügbar",
      "settings.ramUsageWithLimit": "{{used}} MB / {{limit}} GB",
      "settings.ramUsageNoLimit": "{{used}} MB • Aus",
      "settings.ramUnloadedTab": "{{count}} Tab entladen",
      "settings.ramUnloadedTabs": "{{count}} Tabs entladen",
      "settings.systemTitle": "System",
      "settings.systemSubtitle": "Prüfe deine Version und öffne die Erweiterungsverwaltung des Browsers.",
      "settings.checkUpdates": "Nach Updates suchen",
      "settings.openExtensions": "Erweiterungen öffnen",
      "settings.aiTitle": "Lokale KI",
      "settings.aiSubtitle": "Lokales Sprachmodell für Seitenzusammenfassungen verwalten.",
      "settings.aiModelId": "Modell",
      "settings.aiStatusLabel": "Status",
      "settings.removeAiModel": "Entfernen",
      "settings.redownloadAiModel": "Erneut herunterladen",
      "settings.aiReady": "Bereit",
      "settings.aiMissing": "Nicht heruntergeladen",
      "settings.aiError": "Nicht verfügbar",
      "aiModel.status.missing": "Nicht heruntergeladen",
      "aiModel.status.downloading": "Wird heruntergeladen ({{progress}}%)",
      "aiModel.status.ready": "Bereit",
      "aiModel.status.error": "Fehler: {{error}}",
      "aiModel.status.cancelling": "Wird abgebrochen...",
      "aiSummary.downloading": "Modell wird heruntergeladen...",
      "aiSummary.generating": "Zusammenfassung wird generiert...",
      "aiSummary.cancelled": "Zusammenfassung abgebrochen",
      "aiSummary.retry": "Wiederholen",
      "aiSummary.cancel": "Abbrechen",
      "aiSummary.fallback": "Fallback-Zusammenfassung",
      "aiSummary.contextMenu": "Diese Seite zusammenfassen",
      "aiSummary.chatTitle": "Mit dieser Seite chatten",
      "aiSummary.chatPlaceholder": "Stelle eine Frage zu dieser Seite",
      "aiSummary.chatSend": "Fragen",
      "aiSummary.chatThinking": "Denken...",
      "aiSummary.chatUnavailable": "Ich konnte diese Seite nicht beantworten.",
      "privacy.httpsOnlyErrorTitle": "Sichere Verbindung erforderlich",
      "privacy.httpsOnlyErrorBody": "Orion hat diese Anfrage auf HTTPS umgestellt, aber die sichere Version der Website konnte nicht geladen werden.",
      "privacy.httpsOnlyErrorDetail": "Ein Rückfall auf HTTP ist deaktiviert, solange der Nur-HTTPS-Modus aktiv ist.",
      "updates.ready": "Bereit, nach Updates zu suchen.",
      "updates.checking": "Suche...",
      "updates.downloading": "Wird heruntergeladen...",
      "updates.restart": "Zum Aktualisieren neu starten",
      "updates.uptodate": "Aktuell",
      "updates.restarting": "Wird neu gestartet...",
      "modal.rename": "Umbenennen",
      "modal.cancel": "Abbrechen",
      "modal.save": "Speichern",
      "modal.bookmark": "Lesezeichen",
      "bookmark.bar": "Leiste",
      "bookmark.newTab": "Neuer Tab",
      "bookmark.both": "Beide",
      "download.loading": "Wird geladen...",
      "extension.pageTitle": "Erweiterungen",
      "extension.eyebrow": "Erweiterungen",
      "extension.header": "Installierte Erweiterungen verwalten",
      "extension.badge": "Web Store bereit",
      "extension.loadTitle": "Entpackte Erweiterung laden",
      "extension.loadBody": "Installiere Erweiterungen aus dem Chrome Web Store oder lade einen vertrauenswürdigen entpackten Ordner für die lokale Entwicklung.",
      "extension.loadExample": "(z. B. {{extensionPathExample}})",
      "extension.pathPlaceholder": "{{extensionPathPlaceholder}}",
      "extension.loadButton": "Erweiterung laden",
      "extension.installedTitle": "Installierte Erweiterungen",
      "extension.installedNote": "Aus dem Chrome Web Store oder lokalen Ordnern in diesem Browserprofil installiert.",
      "extension.remove": "Entfernen",
      "extension.removeConfirm": "Möchtest du diese Erweiterung wirklich entfernen?",
      "extension.empty": "Keine Erweiterungen installiert.",
      "extension.error": "Fehler beim Laden der Erweiterungen.",
      "extension.success": "Erweiterung erfolgreich geladen!",
      "extension.loadFailure": "Erweiterung konnte nicht geladen werden: {{error}}",
      "extension.invokeFailure": "Fehler beim Aufruf des Erweiterungs-Ladevorgangs: {{error}}",
      "extension.unknown": "Unbekannte Erweiterung",
      "extension.noDescription": "Keine Beschreibung vorhanden.",
      "extension.openWebStore": "Chrome Web Store öffnen",
      "extension.updateButton": "Erweiterungen aktualisieren",
      "extension.updateSuccess": "Prüfung auf Erweiterungsupdates abgeschlossen.",
      "extension.updateFailure": "Erweiterungen konnten nicht aktualisiert werden: {{error}}",
      "extension.webStoreFailure": "Chrome Web Store konnte nicht geöffnet werden: {{error}}",
      "extension.sourceWebStore": "Chrome Web Store",
      "extension.sourceUnpacked": "Entpackt",
      "extension.managed": "Von Orion verwaltet",
      "extension.unknownManifest": "Manifest unbekannt",
      "newtab.pageTitle": "Neuer Tab",
      "newtab.searchPlaceholder": "Web durchsuchen",
      "newtab.removeShortcut": "{{name}} entfernen",
      "reader.title": "Lesemodus",
      "reader.modeLabel": "Lesemodus",
      "reader.loadingArticle": "Artikel wird geladen",
      "reader.enterMode": "Lesemodus",
      "reader.exitMode": "Lesemodus beenden",
      "reader.backToPage": "Zurück zur Seite",
      "reader.theme": "Thema",
      "reader.fontSize": "Schriftgröße",
      "reader.themeSepia": "Sepia",
      "reader.themeLight": "Hell",
      "reader.themeNight": "Nacht",
      "reader.openCanonicalSource": "Kanonische Quelle öffnen",
      "reader.updated": "Aktualisiert {{value}}",
      "reader.unavailable": "Lesemodus nicht verfügbar",
      "reader.unavailableState": "Der Lesemodus ist für diese Seite nicht verfügbar.",
      "reader.unavailableTitle": "Diese Seite konnte nicht konvertiert werden",
      "reader.unavailableSubtitle": "Orion konnte aus dieser Seite keinen verlässlich lesbaren Artikel extrahieren.",
      "reader.dataNotReady": "Die Daten für den Lesemodus sind noch nicht bereit.",
      "reader.loadFailed": "Orion konnte den Lesemodus für diese Seite nicht laden.",
      "reader.untitledArticle": "Unbenannter Artikel"
    }),
    ja: Object.freeze({
      "app.name": "Orion",
      "app.newTab": "新しいタブ",
      "app.loading": "読み込み中...",
      "address.placeholder": "検索または URL を入力",
      "find.placeholder": "ページ内検索...",
      "find.empty": "0/0",
      "toolbar.newTab": "新しいタブ",
      "toolbar.tabGroups": "タブグループ",
      "toolbar.newIncognitoTab": "新しいシークレット タブ ({{primaryModifierLabel}}+Shift+N)",
      "toolbar.closeOthers": "他を閉じる",
      "aiSummary.button": "AI 要約",
      "aiSummary.kicker": "オンデバイス AI",
      "aiSummary.title": "AI 要約",
      "aiSummary.close": "AI 要約パネルを閉じる",
      "aiSummary.loading": "このページを端末上で要約しています...",
      "aiSummary.unavailable": "Orion はこのページを要約できませんでした。",
      "aiSummary.untitled": "無題のページ",
      "aiSummary.localOnly": "端末上",
      "aiSummary.readingTime": "{{minutes}} 分で読めます",
      "profile.addNew": "新しいプロフィールを追加",
      "profile.default": "デフォルト",
      "profile.named": "プロフィール {{index}}",
      "profile.incognito": "シークレット",
      "onboarding.kicker": "ようこそ",
      "onboarding.title": "言語を選択",
      "onboarding.subtitle": "Orion で使用する言語を選んでください。あとで設定から変更できます。",
      "onboarding.persist": "この選択はこの端末に保存され、通常はアプリを再インストールしても保持されます。",
      "history.title": "履歴",
      "history.close": "履歴パネルを閉じる",
      "history.remove": "履歴から削除",
      "history.range.hour": "1 時間",
      "history.range.today": "今日",
      "history.range.week": "今週",
      "history.range.all": "すべて削除",
      "history.confirm.hour": "直近 1 時間の履歴を削除しますか？",
      "history.confirm.today": "今日の履歴を削除しますか？",
      "history.confirm.week": "今週の履歴を削除しますか？",
      "history.confirm.all": "すべての履歴を削除しますか？",
      "bookmarks.title": "ブックマーク",
      "bookmarks.close": "ブックマーク パネルを閉じる",
      "bookmarks.empty": "まだブックマークがありません。",
      "downloads.title": "ダウンロード",
      "downloads.close": "ダウンロード パネルを閉じる",
      "downloads.done": "完了",
      "managedExtension.kicker": "必須の保護",
      "managedExtension.installingTitle": "uBlock Origin Lite をインストール中",
      "managedExtension.installingBody": "このブラウザー プロフィールに必須の広告・トラッカー対策を準備しています。",
      "managedExtension.errorTitle": "uBlock Origin Lite が必要です",
      "managedExtension.errorBody": "Chrome Web Store から必須の拡張機能をインストールできませんでした。接続を確認して再試行してください。",
      "managedExtension.retry": "インストールを再試行",
      "settings.kicker": "ブラウザー操作",
      "settings.title": "設定",
      "settings.close": "設定パネルを閉じる",
      "settings.heroKicker": "カスタマイズ",
      "settings.heroTitle": "Orion を自分仕様に",
      "settings.heroBody": "ブラウザーの見た目と動作を 1 か所で調整できます。変更はすぐに反映されます。",
      "settings.themeTitle": "テーマ",
      "settings.themeSubtitle": "アクセント カラーを選び、レイアウトを調整します。",
      "settings.colorPicker": "カラーピッカー",
      "settings.colorPlaceholder": "色名または 16 進コード",
      "settings.applyColor": "色を適用",
      "settings.discoMode": "ディスコ モード",
      "settings.stopDisco": "ディスコを停止",
      "settings.verticalTabs": "縦型タブ",
      "settings.verticalTabsSub": "タブを左側に固定する",
      "settings.showSeconds": "秒を表示",
      "settings.showSecondsSub": "時刻ウィジェットに秒を表示する",
      "settings.languageTitle": "言語",
      "settings.languageSubtitle": "Orion のインターフェースで使う言語を選択します。",
      "settings.searchTitle": "検索",
      "settings.searchSubtitle": "アドレスバーで通常の文字列を検索するときの検索エンジンを選びます。",
      "settings.searchLabel": "既定の検索エンジン",
      "settings.privacyTitle": "プライバシー",
      "settings.privacySubtitle": "Web リクエストを強化し、すべてのブラウザー セッションでフィンガープリントを抑制します。",
      "settings.httpsOnly": "HTTPS 専用モード",
      "settings.httpsOnlySub": "安全でない HTTP ナビゲーションを HTTPS に切り替え、平文へのフォールバックをブロックします。",
      "settings.antiFingerprinting": "アンチフィンガープリンティング",
      "settings.antiFingerprintingSub": "言語、ハードウェア、タイムゾーン、グラフィック識別子などのブラウザー情報を標準化します。",
      "settings.doh": "DNS-over-HTTPS",
      "settings.dohSub": "対応する名前解決で Cloudflare の厳格なセキュア DNS モードを使用します。",
      "settings.performanceTitle": "パフォーマンス",
      "settings.performanceSubtitle": "Orion の RAM 使用量をこのコンピューターの半分に自動制限します。",
      "settings.ramLimitLabel": "RAM 上限",
      "settings.ramOff": "オフ",
      "settings.ramAutomatic": "自動（{{limit}} GB）",
      "settings.ramAutomaticUnavailable": "自動（利用不可）",
      "settings.ramCustom": "カスタム",
      "settings.ramCustomLabel": "カスタム上限",
      "settings.ramUsageLabel": "現在の使用量",
      "settings.ramWarning": "Orion が上限を超えると、観測されたメモリ使用量が最も多いバックグラウンドタブは再び開いたときに再読み込みされます。スクロール位置、ナビゲーション履歴、フォーム入力など、未保存のページ状態が失われる場合があります。アクティブなタブと音声を再生中のタブは保護されます。",
      "settings.ramUnavailable": "使用量を取得できません",
      "settings.ramUsageWithLimit": "{{used}} MB / {{limit}} GB",
      "settings.ramUsageNoLimit": "{{used}} MB • オフ",
      "settings.ramUnloadedTab": "{{count}} 個のタブをアンロード",
      "settings.ramUnloadedTabs": "{{count}} 個のタブをアンロード",
      "settings.systemTitle": "システム",
      "settings.systemSubtitle": "バージョンを確認し、拡張機能の管理を開きます。",
      "settings.checkUpdates": "アップデートを確認",
      "settings.openExtensions": "拡張機能を開く",
      "settings.aiTitle": "デバイス上AI",
      "settings.aiSubtitle": "ページ要約用のローカル言語モデルを管理します。",
      "settings.aiModelId": "モデル",
      "settings.aiStatusLabel": "ステータス",
      "settings.removeAiModel": "削除",
      "settings.redownloadAiModel": "再ダウンロード",
      "settings.aiReady": "準備完了",
      "settings.aiMissing": "未ダウンロード",
      "settings.aiError": "利用できません",
      "aiModel.status.missing": "未ダウンロード",
      "aiModel.status.downloading": "ダウンロード中 ({{progress}}%)",
      "aiModel.status.ready": "準備完了",
      "aiModel.status.error": "エラー: {{error}}",
      "aiModel.status.cancelling": "キャンセル中...",
      "aiSummary.downloading": "モデルをダウンロード中...",
      "aiSummary.generating": "要約を生成中...",
      "aiSummary.cancelled": "要約がキャンセルされました",
      "aiSummary.retry": "再試行",
      "aiSummary.cancel": "キャンセル",
      "aiSummary.fallback": "フォールバック要約",
      "aiSummary.contextMenu": "このページを要約",
      "aiSummary.chatTitle": "このページとチャット",
      "aiSummary.chatPlaceholder": "このページについて質問",
      "aiSummary.chatSend": "質問",
      "aiSummary.chatThinking": "考え中...",
      "aiSummary.chatUnavailable": "このページから回答できませんでした。",
      "privacy.httpsOnlyErrorTitle": "安全な接続が必要です",
      "privacy.httpsOnlyErrorBody": "Orion はこの要求を HTTPS に切り替えましたが、サイトの安全なバージョンを読み込めませんでした。",
      "privacy.httpsOnlyErrorDetail": "HTTPS 専用モードが有効なため、HTTP へのフォールバックは無効です。",
      "updates.ready": "アップデートを確認する準備ができました。",
      "updates.checking": "確認中...",
      "updates.downloading": "ダウンロード中...",
      "updates.restart": "再起動して更新",
      "updates.uptodate": "最新です",
      "updates.restarting": "再起動中...",
      "modal.rename": "名前を変更",
      "modal.cancel": "キャンセル",
      "modal.save": "保存",
      "modal.bookmark": "ブックマーク",
      "bookmark.bar": "バー",
      "bookmark.newTab": "新しいタブ",
      "bookmark.both": "両方",
      "download.loading": "読み込み中...",
      "extension.pageTitle": "拡張機能",
      "extension.eyebrow": "拡張機能",
      "extension.header": "インストール済み拡張機能を管理",
      "extension.badge": "Web Store 対応",
      "extension.loadTitle": "展開済み拡張機能を読み込む",
      "extension.loadBody": "Chrome Web Store からインストールするか、ローカル開発用に信頼できる展開済み拡張機能フォルダーを読み込みます。",
      "extension.loadExample": "(例: {{extensionPathExample}})",
      "extension.pathPlaceholder": "{{extensionPathPlaceholder}}",
      "extension.loadButton": "拡張機能を読み込む",
      "extension.installedTitle": "インストール済み拡張機能",
      "extension.installedNote": "Chrome Web Store またはこのブラウザー プロフィールのローカル フォルダーからインストールされています。",
      "extension.remove": "削除",
      "extension.removeConfirm": "この拡張機能を削除してもよろしいですか？",
      "extension.empty": "拡張機能はまだありません。",
      "extension.error": "拡張機能の読み込み中にエラーが発生しました。",
      "extension.success": "拡張機能を読み込みました。",
      "extension.loadFailure": "拡張機能の読み込みに失敗しました: {{error}}",
      "extension.invokeFailure": "拡張機能の読み込み呼び出しでエラーが発生しました: {{error}}",
      "extension.unknown": "不明な拡張機能",
      "extension.noDescription": "説明はありません。",
      "extension.openWebStore": "Chrome Web Store を開く",
      "extension.updateButton": "拡張機能の更新を確認",
      "extension.updateSuccess": "拡張機能の更新確認が完了しました。",
      "extension.updateFailure": "拡張機能を更新できませんでした: {{error}}",
      "extension.webStoreFailure": "Chrome Web Store を開けませんでした: {{error}}",
      "extension.sourceWebStore": "Chrome Web Store",
      "extension.sourceUnpacked": "展開済み",
      "extension.managed": "Orion により管理",
      "extension.unknownManifest": "マニフェスト不明",
      "newtab.pageTitle": "新しいタブ",
      "newtab.searchPlaceholder": "ウェブを検索",
      "newtab.removeShortcut": "{{name}} を削除",
      "reader.title": "リーダー",
      "reader.modeLabel": "リーダーモード",
      "reader.loadingArticle": "記事を読み込み中",
      "reader.enterMode": "リーダーモード",
      "reader.exitMode": "リーダーモードを終了",
      "reader.backToPage": "ページに戻る",
      "reader.theme": "テーマ",
      "reader.fontSize": "文字サイズ",
      "reader.themeSepia": "セピア",
      "reader.themeLight": "ライト",
      "reader.themeNight": "ナイト",
      "reader.openCanonicalSource": "正規ソースを開く",
      "reader.updated": "更新 {{value}}",
      "reader.unavailable": "リーダーを利用できません",
      "reader.unavailableState": "このページではリーダーモードを利用できません。",
      "reader.unavailableTitle": "このページは変換できませんでした",
      "reader.unavailableSubtitle": "Orion はこのページから十分に読みやすい記事を抽出できませんでした。",
      "reader.dataNotReady": "リーダーデータの準備がまだできていません。",
      "reader.loadFailed": "Orion はこのページのリーダーモードを読み込めませんでした。",
      "reader.untitledArticle": "無題の記事"
    })
  });

  function sanitizeLocale(locale) {
    return SUPPORTED_LOCALES.includes(locale) ? locale : null;
  }

  function resolveLocale(locale, fallback = DEFAULT_LOCALE) {
    return sanitizeLocale(locale) || fallback;
  }

  function getIntlLocale(locale) {
    return INTL_LOCALES[resolveLocale(locale)] || INTL_LOCALES[DEFAULT_LOCALE];
  }

  function getMessages(locale) {
    return TRANSLATIONS[resolveLocale(locale)] || TRANSLATIONS[DEFAULT_LOCALE];
  }

  function normalizeUiPlatform(platform) {
    const value = String(platform == null ? "" : platform).trim().toLowerCase();
    if (!value) return "linux";

    if (
      value === "mac"
      || value === "macos"
      || value === "darwin"
      || value === "osx"
      || value.includes("mac")
      || value.includes("darwin")
      || value.includes("os x")
    ) {
      return "mac";
    }

    if (
      value === "windows"
      || value === "win32"
      || value === "win64"
      || value.includes("windows")
      || /\bwin(?:32|64)?\b/.test(value)
    ) {
      return "windows";
    }

    if (value === "linux" || value.includes("linux") || value.includes("x11")) {
      return "linux";
    }

    return "linux";
  }

  function getUiPlatformText(locale, platform) {
    const resolvedLocale = resolveLocale(locale);
    const resolvedPlatform = normalizeUiPlatform(platform);
    const modifierLabels = UI_PLATFORM_PRIMARY_MODIFIERS[resolvedPlatform] || UI_PLATFORM_PRIMARY_MODIFIERS.linux;
    const extensionPath = UI_PLATFORM_EXTENSION_PATHS[resolvedPlatform] || UI_PLATFORM_EXTENSION_PATHS.linux;

    return {
      platform: resolvedPlatform,
      primaryModifierLabel: modifierLabels[resolvedLocale] || modifierLabels.default || "Ctrl",
      extensionPathExample: extensionPath,
      extensionPathPlaceholder: extensionPath
    };
  }

  function interpolate(template, vars = {}) {
    return String(template).replace(/\{\{(\w+)\}\}/g, (_, key) => {
      return Object.prototype.hasOwnProperty.call(vars, key) ? String(vars[key]) : "";
    });
  }

  function t(locale, key, vars = {}) {
    const messages = getMessages(locale);
    const fallback = TRANSLATIONS[DEFAULT_LOCALE];
    const template = messages[key] != null ? messages[key] : fallback[key];
    if (template == null) return key;
    return interpolate(template, vars);
  }

  function getLanguageOptions() {
    return LANGUAGE_OPTIONS.slice();
  }

  function getProfileName(locale, index) {
    if (index === 0) return t(locale, "profile.default");
    return t(locale, "profile.named", { index });
  }

  function getIncognitoProfileName(locale) {
    return t(locale, "profile.incognito");
  }

  function isGeneratedProfileName(name, index) {
    if (!name) return false;
    return SUPPORTED_LOCALES.some((locale) => {
      return name === getProfileName(locale, index) || name === getIncognitoProfileName(locale);
    });
  }

  return {
    DEFAULT_LOCALE,
    INTL_LOCALES,
    SUPPORTED_LOCALES,
    TRANSLATIONS,
    getIntlLocale,
    getIncognitoProfileName,
    getLanguageOptions,
    getMessages,
    getProfileName,
    getUiPlatformText,
    isGeneratedProfileName,
    normalizeUiPlatform,
    resolveLocale,
    sanitizeLocale,
    t
  };
});
